CoreTestPage:
    pattern:  /xwc/
    defaults: { _controller: TangentLabs\XwcCoreBundle:XwcCore:index }
PageShow:
    pattern:  /show/:route
    defaults: { _controller: TangentLabs\XwcCoreBundle:Page:show }
#PageEdit:
#    pattern:  /edit/:route
#    defaults: { _controller: TangentLabs\XwcCoreBundle:Page:edit } 
#PageCreate:
#    pattern:  /new/:name
#    defaults: { _controller: TangentLabs\XwcCoreBundle:Page:create }    
#Page:
#pattern:      /view/:page.:_format
#defaults:     { _controller: TangentLabs\XwcCoreBundle:Page:show, _format: html }
#requirements: { _format: (html|xml|json) }